// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKddIB_o64NYF11FyjUl8HC9LM8qeLgsw',
    appId: '1:461523626871:web:59ba684849663e6d750f72',
    messagingSenderId: '461523626871',
    projectId: 'todoapp-6896f',
    authDomain: 'todoapp-6896f.firebaseapp.com',
    storageBucket: 'todoapp-6896f.appspot.com',
    measurementId: 'G-CVS7S1PLSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8vST7WXICBky6_pldh1C-xtMD5MeUtA',
    appId: '1:461523626871:android:c93f6f52142b75db750f72',
    messagingSenderId: '461523626871',
    projectId: 'todoapp-6896f',
    storageBucket: 'todoapp-6896f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFfDkyT9EvuWgaaI-WbZG70vpwFzBF8Q',
    appId: '1:461523626871:ios:7f1cfae50ec8c3a0750f72',
    messagingSenderId: '461523626871',
    projectId: 'todoapp-6896f',
    storageBucket: 'todoapp-6896f.appspot.com',
    iosBundleId: 'com.example.todoFullApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJFfDkyT9EvuWgaaI-WbZG70vpwFzBF8Q',
    appId: '1:461523626871:ios:7f1cfae50ec8c3a0750f72',
    messagingSenderId: '461523626871',
    projectId: 'todoapp-6896f',
    storageBucket: 'todoapp-6896f.appspot.com',
    iosBundleId: 'com.example.todoFullApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKddIB_o64NYF11FyjUl8HC9LM8qeLgsw',
    appId: '1:461523626871:web:5f2ed6a536e4e409750f72',
    messagingSenderId: '461523626871',
    projectId: 'todoapp-6896f',
    authDomain: 'todoapp-6896f.firebaseapp.com',
    storageBucket: 'todoapp-6896f.appspot.com',
    measurementId: 'G-XF80RMWNMG',
  );
}
